/**
 * Engineering timeline entries, newest first.
 * To add an entry: append an object — the timeline page renders and
 * filters automatically. `kind` drives the filter chips and node color.
 */

export type TimelineKind =
  | "education"
  | "work"
  | "project"
  | "milestone"
  | "target";

export interface TimelineEntry {
  /** Display date, e.g. "Aug 2025" or "2022 – 2024". */
  date: string;
  /** Sort key: approximate start date, ISO format. */
  sort: string;
  title: string;
  kind: TimelineKind;
  description: string;
  /** Optional link to a project page or external resource. */
  href?: string;
  /** Future goals render dashed/dimmed. */
  future?: boolean;
}

export const timeline: TimelineEntry[] = [
  {
    date: "2029 (projected)",
    sort: "2029-05-01",
    title: "B.S. Mechanical Engineering — Aerospace Emphasis",
    kind: "target",
    description:
      "Expected graduation from Utah State University.",
    future: true,
  },
  {
    date: "Summer 2027",
    sort: "2027-05-01",
    title: "Engineering internship",
    kind: "target",
    description:
      "Primary near-term objective: a mechanical or aerospace engineering internship. Top target is the Space Dynamics Laboratory, the UARC on USU's campus.",
    future: true,
  },
  {
    date: "2026 – 2027",
    sort: "2026-12-01",
    title: "SolidWorks CSWA certification",
    kind: "target",
    description:
      "Certified SolidWorks Associate exam — turning \"familiar with SolidWorks\" into a verified credential.",
    future: true,
  },
  {
    date: "Jun 2026",
    sort: "2026-06-20",
    title: "Pickleball launcher — design phase complete",
    kind: "project",
    description:
      "Sized motors, selected drive wheels and controllers, and finalized a sub-$100 bill of materials for a dual-wheel ball launcher. Build and test campaign in progress.",
    href: "/projects/pickleball-launcher",
  },
  {
    date: "Jun 2026",
    sort: "2026-06-10",
    title: "First engineering internship applications",
    kind: "milestone",
    description:
      "Applied to Chromalox (weld engineering, manufacturing engineering), Sure Steel (mechanical designer), and Parker Hannifin — with tailored resumes and cover letters generated by my own tooling.",
  },
  {
    date: "Spring 2026",
    sort: "2026-03-01",
    title: "Job search automation tool",
    kind: "project",
    description:
      "Built a multi-module Python application that scrapes job boards, scores listings with a locally-hosted LLM, and generates tailored application documents.",
    href: "/projects/job-search-tool",
  },
  {
    date: "Aug 2025",
    sort: "2025-08-15",
    title: "Utah State University",
    kind: "education",
    description:
      "Started the Mechanical Engineering program with an Aerospace emphasis. 4.0 institutional GPA through the first year.",
  },
  {
    date: "Feb 2025",
    sort: "2025-02-01",
    title: "Dutch Bros — Barista",
    kind: "work",
    description:
      "High-volume service work in Logan, UT, carried alongside a full engineering course load.",
  },
  {
    date: "Sep 2024",
    sort: "2024-09-01",
    title: "UPS — Package Handler",
    kind: "work",
    description:
      "Package sorting and loading at the Napavine, WA hub. Daily throughput targets, physical logistics, zero-error sort discipline.",
  },
  {
    date: "2022 – 2024",
    sort: "2022-09-01",
    title: "Centralia College — Associate's Degree",
    kind: "education",
    description:
      "Completed an Associate's degree in Washington, including first programming coursework in Python. Transferred into USU engineering.",
  },
  {
    date: "2020 – 2022",
    sort: "2020-06-01",
    title: "Burgerville — Crew Member",
    kind: "work",
    description:
      "First job. Kitchen operations in Centralia, WA — where an interest in process optimization started showing up in practice.",
  },
  {
    date: "High school",
    sort: "2020-01-01",
    title: "Eagle Scout — Boy Scouts of America",
    kind: "milestone",
    description:
      "Earned the BSA's highest rank (~4% of Scouts reach it): a multi-year effort capped by planning and leading a community service project end to end.",
  },
];
